### ISSUE TITLE
After installation, I get "This is not supposed to happen"

### ISSUE THREAD

**Issue by ketil-malde** [biigle/biigle#15]
I followed the instructions for a non-SSL setup, and docker-compose appeared to bring up the set of services correctly.  But connecting to my host with a web browser only resulted in the message:

> This is not supposed to happen. You probably just discovered a bug.
>
> Please notify the BIIGLE administrators with the exact steps to reproduce this error.

I tried `docker-compose logs`, but I can't see anything out of the ordinary.

I tried to connect with the `artisan` shell, but in spite of declaring itself to be `BusyBox`, it doesn't seem to understand shell commands.  

In sum, I have no idea how to debug this, and the documentation doesn't seem to give any guidance.

**Comment by mzur** [comment]
Please have a look in `storage/logs`. There should be a logfile with an error message there. Please post the error here.

**Comment by ketil-malde** [comment]
```
[2022-01-26 10:03:53] production.ERROR: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. {"exception":"[object] (RuntimeException(code: 0): The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. at /var/www/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43)
[stacktrace]
```

This looks suspicious, I guess?

**Comment by ketil-malde** [comment]
Seems to work fine now.

Maybe better error reporting, documentation of logs, or verification of configuration settings? :-)

But thanks for the quick help.

**Comment by mzur** [comment]
Noted (#16), thanks for the feedback!
